version: "3.8"
services:
  producer:
    image: cloudmore/producer-service:1.0-SNAPSHOT
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      KAFKA_TOPIC: wage
    ports:
      - 8091:8091

  consumer:
    image: cloudmore/consumer-service:1.0-SNAPSHOT
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      KAFKA_TOPIC: wage
      JDBC_DATABASE_URL: 'jdbc:mysql://db:3306/accounting'
      TAX_RATE: 1.1
    ports:
      - 8092:8092

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: accounting
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8090:8080

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_TOOLS_LOG4J_LOGLEVEL: WARN
      KAFKA_LOG4J_LOGGERS=kafka: WARN,state.change.logger=WARN,kafka.controller=WARN
    depends_on:
      - zookeeper

volumes:
  mysql:
