version: "3.8"
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: accounting
    volumes:
    - mysql:/var/lib/mysql
    ports:
    - 3306:3306

  adminer:
    image: adminer
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8090:8080

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_TOOLS_LOG4J_LOGLEVEL: WARN
      KAFKA_LOG4J_LOGGERS=kafka: WARN,state.change.logger=WARN,kafka.controller=WARN
    depends_on:
      - zookeeper

volumes:
  mysql:
